[theme]
primaryColor = "#0A6EBD"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
